# Generated by Django 4.2.16 on 2024-12-05 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reconocimientoFacial', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('n_id_asistencia', models.BigIntegerField(primary_key=True, serialize=False)),
                ('t_hora_inicio', models.DateTimeField(blank=True, null=True)),
                ('t_hora_fin', models.DateTimeField(blank=True, null=True)),
                ('c_estado', models.CharField(blank=True, max_length=1, null=True)),
                ('d_fecha', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'asistencia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Dependencia',
            fields=[
                ('n_id_dependencia', models.BigIntegerField(primary_key=True, serialize=False)),
                ('v_descripcion', models.CharField(blank=True, max_length=70, null=True)),
                ('v_abreviatura', models.CharField(blank=True, max_length=70, null=True)),
            ],
            options={
                'db_table': 'dependencia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EspacioAula',
            fields=[
                ('n_id_espacio_aula', models.BigIntegerField(primary_key=True, serialize=False)),
                ('n_capacidad', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'espacio_aula',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EspacioAulaPersonal',
            fields=[
                ('n_id_aula_personal', models.BigIntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'espacio_aula_personal',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EspacioTurno',
            fields=[
                ('n_id_espacio_turno', models.BigIntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'espacio_turno',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('n_id_evento', models.BigIntegerField(primary_key=True, serialize=False)),
                ('v_cod_evento', models.CharField(blank=True, max_length=7, null=True)),
                ('v_nombre', models.CharField(blank=True, max_length=90, null=True)),
                ('d_fecha_inicio', models.DateField(blank=True, null=True)),
                ('d_fecha_fin', models.DateField(blank=True, null=True)),
                ('c_estado', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'db_table': 'evento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LogReconocimiento',
            fields=[
                ('n_id_log_reconocimiento', models.BigIntegerField(primary_key=True, serialize=False)),
                ('v_evento', models.CharField(blank=True, max_length=55, null=True)),
                ('v_tabla', models.CharField(blank=True, max_length=55, null=True)),
                ('cl_row_data', models.TextField(blank=True, null=True)),
                ('d_fec_registro', models.DateField(blank=True, null=True)),
                ('d_fec_actividad', models.DateField(blank=True, null=True)),
                ('v_ip_usuario', models.CharField(blank=True, max_length=55, null=True)),
            ],
            options={
                'db_table': 'log_reconocimiento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('n_id_personal', models.BigIntegerField(primary_key=True, serialize=False)),
                ('v_cod_personal', models.CharField(blank=True, max_length=7, null=True)),
                ('v_nombre', models.CharField(blank=True, max_length=55, null=True)),
                ('v_apellido_paterno', models.CharField(blank=True, max_length=55, null=True)),
                ('v_apellido_materno', models.CharField(blank=True, max_length=55, null=True)),
                ('v_correo_institucional', models.CharField(blank=True, max_length=80, null=True)),
                ('n_telefono_contacto', models.BigIntegerField(blank=True, null=True)),
                ('n_num_doc', models.BigIntegerField(blank=True, null=True)),
                ('v_disponibilidad', models.CharField(blank=True, max_length=15, null=True)),
                ('c_estado', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'db_table': 'personal',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('n_id_reporte', models.BigIntegerField(primary_key=True, serialize=False)),
                ('v_tipo_reporte', models.CharField(blank=True, max_length=70, null=True)),
                ('d_fecha_generacion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'reporte',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RepositorioImagen',
            fields=[
                ('n_id_rep_imagen', models.BigIntegerField(primary_key=True, serialize=False)),
                ('imagen_biometrica', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'repositorio_imagen',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoPersonal',
            fields=[
                ('n_id_tipo_personal', models.BigIntegerField(primary_key=True, serialize=False)),
                ('v_descripcion', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'tipo_personal',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('n_id_turno', models.BigIntegerField(primary_key=True, serialize=False)),
                ('t_hora_inicio', models.DateTimeField(blank=True, null=True)),
                ('t_hora_fin', models.DateTimeField(blank=True, null=True)),
                ('d_fecha', models.DateField(blank=True, null=True)),
                ('c_estado', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'db_table': 'turno',
                'managed': False,
            },
        ),
    ]
