# Generated by Django 4.2.16 on 2024-12-05 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reconocimientoFacial', '0003_actividades'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Actividades',
        ),
    ]
